- package:
  - name: Foundry
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Assembler.C.AST
        - identifier:
          - CContinue
          - CDefine
          - CParen
          - CTernOp
          - CTypeIdent
          - CUndefine
          - prettyLines
      - module:
        - name: IceBurn.Ice40Board
        - identifier:
          - boardGetSerial
          - flashGetStatus
          - flashSetWritable
          - flashWaitDone
      - module:
        - name: Simulator.Elm.AST
        - identifier:
          - ElmComment
          - ElmCons
          - ElmMonOp
          - ElmTuplePat
      - module:
        - name: Utils
        - identifier:
          - decodeWord16
          - decodeWord64
          - decodeWord8
          - encodeWord16
          - encodeWord64
          - encodeWord8

