- package:
  - name: iceburn
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: IceBurn.Ice40Board
        - identifier:
          - boardGetSerial
          - flashGetStatus
          - flashSetWritable
          - flashWaitDone
- package:
  - name: simple-elm-ast
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Language.Elm.Internal
        - identifier:
          - ElmPrec2
          - ElmPrec3
          - ElmPrec4
          - ElmPrec6
          - ElmPrec7
          - ElmPrec8

