name:                Foundry
version:             0.1.0.0
github:              "nixCodeX/Foundry"
license:             GPL-3
author:              "Jonathan Tanner"
maintainer:          "jonathan.tanner@sjc.ox.ac.uk"
copyright:           "2019 Jonathan Tanner"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Easy to use toolchain for building simple processors
# category:            Hardware, Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nixCodeX/Foundry#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  dependencies:
    - array
    - containers
    - filepath
    - lens
    - mtl
    - process
    - split
    - temporary
    - transformers

executables:
  Foundry-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Foundry
      - filepath
      - mtl
#  Foundry-Language-Server-exe:
#    main:                Main.hs
#    source-dirs:         language_server
#    dependencies:
#      - Foundry
#      - haskell-lsp
#      - haskell-lsp-types
#      - lens
#      - mtl
#      - text

data-files:
  - assembler/assembler.c
  - assembler/assembler.h
  - assembler/plugin.h
  - assembler/utils.c
  - assembler/utils.h

tests:
  Parser-test:
    main:                test/Parser.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Foundry
  CodeGen-test:
    main:                test/CodeGen.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Foundry
  HLint-test:
    main:                test/HLint.hs
    dependencies:
      - Foundry
      - hlint
