// Handwritten simple C assembler intended to be generated by the toolchain

# include <stdio.h>
# include <stdlib.h>
# include <string.h>

# define INST_WIDTH 1

typedef struct _labels_t {
  char* name;
  int loc;
  struct _labels_t* next;
} labels_t;

labels_t* findLabel(char* name, labels_t* labels) {
  while (labels != NULL && strcmp(name, labels->name) != 0) {
    labels = labels->next;
  }
  return labels;
}

char* encInt(int n, int width) {
  char* bits = calloc(sizeof(char), width);
  for (int i = 0; i < width; ++i) {
    strcat(bits, (n >> i) & 1 ? "1" : "0");
  }
  return bits;
}

char* encReg(char* reg) {

}

void ignoreWhitespace(FILE* f, int* line) {
  char c;
  do {
    c = fgetc(f);
    if (c == '\n') *line += 1;
  } while (c == ' ' || c == '\n');
  ungetc(c, f);
}

int main(int argc, char* argv[]) {
  if (argc != 3) {
    printf("Wrong number of command line arguments, USAGE %s <input> <output>", argv[0]);
    return 1;
  }
  FILE* fIn  = fopen(argv[1], "r");
  if (fIn == NULL) {
    printf("Input file %s does not exist", argv[1]);
    return 1;
  }
  FILE* fOut = fopen(argv[2], "w");
  if (fOut == NULL) {
    printf("Output file %s does not exist", argv[2]);
    return 1;
  }

  labels_t* labels = NULL;
  int loc = 0;
  int line = 1;
  while (!feof(fIn)) {
    char firstWord[32];
    ignoreWhitespace(fIn, &line);
    if (fscanf(fIn, "%31s", firstWord)) {
      int firstWordLen = strlen(firstWord);
      ignoreWhitespace(fIn, &line);
      if (firstWord[firstWordLen - 1] == ':') {
        char* name = malloc(firstWordLen);
        strncpy(name, firstWord, firstWordLen - 1);
        name[firstWordLen - 1] = '\0';
        labels_t* new_labels = malloc(sizeof(labels_t));
        new_labels->name = name;
        new_labels->loc  = loc;
        new_labels->next = labels;
        labels = new_labels;
      } else {
        if (strcmp(firstWord, "halt") == 0) {
        } else if (strcmp(firstWord, "ldi") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            printf("line %d: ldi instruction takes an Int argument \n", line);
            return 2;
          }
        } else if (strcmp(firstWord, "add") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            printf("line %d: add instruction takes an Int argument \n", line);
            return 2;
          }
        } else if (strcmp(firstWord, "sub") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            printf("line %d: sub instruction takes an Int argument \n", line);
            return 2;
          }
        } else if (strcmp(firstWord, "ldm") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            printf("line %d: ldm instruction takes an Int argument \n", line);
            return 2;
          }
        } else if (strcmp(firstWord, "stm") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            printf("line %d: stm instruction takes an Int argument \n", line);
            return 2;
          }
        } else if (strcmp(firstWord, "jp") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            char lab[32];
            if (fscanf(fIn, "%31s", &lab) == 0) {
              printf("line %d: jp instruction takes an Int argument \n", line);
              return 2;
            }
          }
        } else if (strcmp(firstWord, "jpz") == 0) {
          int n;
          if (fscanf(fIn, "%d", &n) == 0) {
            char lab[32];
            if (fscanf(fIn, "%31s", &lab) == 0) {
              printf("line %d: jpz instruction takes an Int argument \n", line);
              return 2;
            }
          }
        } else {
          printf("line %d: instruction %s not recognised", line, firstWord);
          return 2;
        }
        loc += INST_WIDTH;
      }
    }
  }

  rewind(fIn);

  while (!feof(fIn)) {
    char firstWord[32];
    ignoreWhitespace(fIn, &line);
    if (fscanf(fIn, "%31s", firstWord)) {
      int firstWordLen = strlen(firstWord);
      ignoreWhitespace(fIn, &line);
      if (firstWord[firstWordLen - 1] == ':') {
        // Label, do nothing
      } else if (strcmp(firstWord, "halt") == 0) {
        fprintf(fOut, "%s\n", "00000000");
      } else if (strcmp(firstWord, "ldi") == 0) {
        int n;
        fscanf(fIn, "%d", &n);
        fprintf(fOut, "%s%s\n", "0001", encInt(n, 4));
      } else if (strcmp(firstWord, "add") == 0) {
        int n;
        fscanf(fIn, "%d", &n);
        fprintf(fOut, "%s%s\n", "0010", encInt(n, 4));
      } else if (strcmp(firstWord, "sub") == 0) {
        int n;
        fscanf(fIn, "%d", &n);
        fprintf(fOut, "%s%s\n", "0011", encInt(n, 4));
      } else if (strcmp(firstWord, "ldm") == 0) {
        int n;
        fscanf(fIn, "%d", &n);
        fprintf(fOut, "%s%s\n", "0100", encInt(n, 4));
      } else if (strcmp(firstWord, "stm") == 0) {
        int n;
        fscanf(fIn, "%d", &n);
        fprintf(fOut, "%s%s\n", "0101", encInt(n, 4));
      } else if (strcmp(firstWord, "jp") == 0) {
        int n;
        if (fscanf(fIn, "%d", &n) == 0) {
          char lab[32];
          fscanf(fIn, "%31s", lab);
          n = findLabel(lab, labels)->loc;
        }
        fprintf(fOut, "%s%s\n", "0110", encInt(n, 4));
      } else if (strcmp(firstWord, "jpz") == 0) {
        int n;
        if (fscanf(fIn, "%d", &n) == 0) {
          char lab[32];
          fscanf(fIn, "%31s", lab);
          n = findLabel(lab, labels)->loc;
        }
        fprintf(fOut, "%s%s\n", "0111", encInt(n, 4));
      }
    }
  }

  fclose(fIn);
  fclose(fOut);

  return 0;
}
