name:                foundry
version:             0.1.0.0
github:              "nixCodeX/Foundry"
license:             GPL-3
author:              "Jonathan Tanner"
maintainer:          "jonathan.tanner@sjc.ox.ac.uk"
copyright:           "2019 Jonathan Tanner"

# Metadata used when publishing your package
# synopsis:            Easy to use toolchain for building simple processors
# category:            Hardware, Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nixCodeX/Foundry#readme>

dependencies:
  - base >= 4.7 && < 5.0

library:
  source-dirs: src
  exposed-modules:
    - CallSynth
    - GenAssembler
    - GenSimulator
    - GenVerilog
    - Web

  build-tools:
    - alex
    - happy
  dependencies:
    - bit-list
    - bytestring
    - classy-prelude
    - containers
    - directory
    - filepath
    - foundry-parser
    - group
    - iceburn
    - maps
    - mono-traversable
    - mtl
    - process
    - simple-c-ast
    - simple-elm-ast
    - simple-verilog-ast
    - snap-core
    - snap-server
    - temporary
    - text
    - word-encoder

executables:
  foundry:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - classy-prelude
      - containers
      - filepath
      - foundry
      - foundry-parser
      - iceburn
      - mtl
      - text

data-files:
  - assembler/assembler.c
  - assembler/assembler.h
  - assembler/plugin.h
  - assembler/utils.c
  - assembler/utils.h
  - simulator/elm/elm.json
  - simulator/elm/src/Bootstrap/Form/Range.elm
  - simulator/elm/src/Hex.elm
  - simulator/elm/src/Icons.elm
  - simulator/elm/src/Interface.elm
  - simulator/elm/src/IntWidths.elm
  - simulator/elm/src/List/Pad.elm
  - simulator/elm/src/WebUSB.elm
  - simulator/index.html
  - simulator/purs/bower.json
  - simulator/purs/src/ElmPorts.js.append
  - simulator/purs/src/ElmPorts.purs
  - simulator/purs/src/Ice40Board.purs
  - simulator/purs/src/IceBurn.purs
  - simulator/purs/src/Main.purs
  - simulator/purs/src/WebUSB.js
  - simulator/purs/src/WebUSB.purs
  - verilog/pinDef.pcf
  - verilog/prescaler.v
  - verilog/ram.v
  - verilog/single_trigger.v
  - verilog/wrapper.v

tests:
  Elm-test:
    main:                test/simulator/Elm.hs
    dependencies:
      - directory
      - filepath
      - process
  HLint-test:
    main:                test/HLint.hs
    dependencies:
      - hlint
