name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@v1
    - name: Run tests
      run: stack test
    - name: Install executable
      run: stack install

