name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create .stack
      run: mkdir $GITHUB_WORKSPACE/.stack
    - name: Cache .stack
      uses: actions/cache@v1
      with:
        path: .stack
        key: home_stack
    - name: Symbolic link to .stack
      run: ln -s $GITHUB_WORKSPACE/.stack $HOME/.stack
    - name: Install libusb-dev
      run: sudo apt install libusb-1.0-0-dev
    - name: Install elm-test
      run: npm install -g elm-test
    - name: Run tests
      run: stack test
    - name: Add to path
      run: export PATH=$HOME/.local/bin:$PATH
    - name: Install executable
      run: stack install
    - name: Show size of .stack dir
      run: du -sh $GITHUB_WORKSPACE/.stack
    - name: Show size of .stack subdirs
      run: du -sh $GITHUB_WORKSPACE/.stack/*

